spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/central_storage
    driver-class-name: org.postgresql.Driver
    username: myuser
    password: mypassword
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    template:
      default-topic: my-topic
    consumer:
      group-id: myGroup

# java -jar your-application.jar --spring.profiles.active=prod
