# java -jar your_application.jar --spring.profiles.active=prod

# port
server:
  port: 8082

# slf4j
logging:
  level:
    root: INFO

spring:
  # postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/central_storage
    driver-class-name: org.postgresql.Driver
    username: myuser
    password: mypassword
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  # kafka
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    template:
      default-topic: my-topic
    consumer:
      group-id: myGroup

# opensearch
opensearch:
  ssl:
    trust-store: /Users/donggyeong/develop/now/opensearch/files/cert/files/opensearch-truststore # /full/path/to/keystore
    trust-store-password: IndexerPassword12#  # password-to-keystore
  host: localhost
  port: 9200
  scheme: https
  username: admin
  password: IndexerPassword12#
